"""empty message

Revision ID: 869df1c0117d
Revises: 6da2043681a9
Create Date: 2021-09-12 21:22:44.871769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869df1c0117d'
down_revision = '6da2043681a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'looking_for_venues')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('looking_for_venues', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
